package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Thursday, 11 April 2024 22:43:10 o'clock IST
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
