package PrimeApp;


/**
* PrimeApp/PrimeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Prime.idl
* Wednesday, 10 April 2024 17:31:47 o'clock IST
*/

public interface PrimeOperations 
{
  String CheckPrime (int num);
  void shutdown ();
} // interface PrimeOperations
