package PrimeApp;


/**
* PrimeApp/Prime.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Prime.idl
* Wednesday, 10 April 2024 17:31:47 o'clock IST
*/

public interface Prime extends PrimeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Prime
